name: Reproduce Python 3.14.0rc1 asyncio introspection feature
on:
  push:
  workflow_dispatch:
jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python-install-method }}.  Try to reproduce Python 3.14.0rc1 asyncio introspection feature
    strategy: 
      fail-fast: false
      matrix:
        os: [
          "macos-latest",
          "ubuntu-24.04",
          "windows-latest",
        ]
        python-install-method: [via-uv, via-setup-python]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      if: matrix.python-install-method == 'via-uv'
      uses: astral-sh/setup-uv@v4
    - name: Create Python 3.14.0rc1 venv
      if: matrix.python-install-method == 'via-uv'
      run: uv venv .venv --python=3.14.0rc1

    - uses: actions/setup-python@v5
      if: matrix.python-install-method == 'via-setup-python'
      with:
        python-version: "3.14.0-rc.1"

    - name: Run example app and asyncio pstree
      shell: bash
      run: |
        if [ "${{ matrix.python-install-method }}" == "via-uv" ]; then
          source .venv/bin/activate
        fi
        python asyncio_example.py &
        sudo python -m asyncio pstree $!
